### ISSUE TITLE
External links missing `rel=noopener`

### ISSUE THREAD

**Issue by brkn** [pyistanbul/pycon-tr-website#33]
It's not safe to have href's with `target=_blank`, they should have `rel=noopener`.

[This site](https://mathiasbynens.github.io/rel-noopener/) can explain it in more detail better than me.

**Comment by halilkaya** [comment]
Hey @brkn ,

You're absolutely right! Thanks a lot for your warning.

I have deployed this fix with PR #40 🎉 

See you at PyCon Turkey 2020! 🙌
