### ISSUE TITLE
Adding a new subtitle in "The Venue" section

### ISSUE THREAD

**Issue by gkmngrgn** [pyistanbul/pycon-tr-website#7]
Hi team,

I thought that I could do it myself, but it seems I need your help for fixing styles. But first of all, let's decide about the idea and the content.

### What do I want to add?

**Accessibility**
We want to remove all the barriers to join the meeting. So:
- It's possible to enter the venue with a wheelchair. You can use elevators and there are accessible toilets.
- The university has disabled parking facilities.
- We have retreat spots for people with sensory issues.
- At the venue, you can always contact to an attendant in any case. We will help you.

If you have an accessibility need to be covered at our events, please [send us an email](a-valid-email-address@pycon.org). We’ll do our best to help.

### Where do I want to add the new content?

In "The Venue" section, after "Get Directions" button.

![image](https://user-images.githubusercontent.com/72323/69484206-06e3cc00-0e31-11ea-8cd5-85fe16bfbafc.png)

**Comment by halilkaya** [comment]
Hi @gkmngrgn ,

Thanks for your report! We have just updated the section with the accessibility text that you mentioned in the issue. It will be deployed soon.

Thanks again! 🎉
